######################################################################
# Automatically generated by qmake (1.07a) Tue May 6 10:54:13 2008
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += thpc_thread.h ui_thpc.h
INTERFACES += thpc.ui
SOURCES += main.cpp thpc_thread.cpp ../../sclient.cpp ../../packet_t.cpp
